# Generated by Django 5.2.8 on 2025-12-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_make_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
