# Generated by Django 5.2.8 on 2025-11-13 00:02

from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[None] = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "ci",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
